before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:
  - build
  - deploy

build:
  stage: build
  image: "klakegg/hugo"
  script:
    - git submodule update --init --recursive
    - hugo -D
  artifacts:
    paths:
      - public
  only:
    - master

deploy-live:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
  image: "edbizarro/gitlab-ci-pipeline-php:8.0"
  script:
    - rsync -avz --delete public/* $SSH_CONNECTION